CREATE TABLE ACCOUNT(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  BALANCE DECIMAL(10,2)
);

CREATE TABLE PAYMENT(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FROM_ACCOUNT BIGINT NOT NULL,
  TO_ACCOUNT BIGINT NOT NULL,
  AMOUNT DECIMAL(10,2)  NOT NULL,
  DESCRIPTION VARCHAR(128)
);

ALTER TABLE PAYMENT ADD FOREIGN KEY (FROM_ACCOUNT) REFERENCES ACCOUNT(ID);
ALTER TABLE PAYMENT ADD FOREIGN KEY (TO_ACCOUNT) REFERENCES ACCOUNT(ID);